;=====================
PRO FICLOSE, DUMMY
;=====================
COMMON FILE_PLOT, PLTFILE, PLT_UNIT, DEV, PLT_DEV

ON_ERROR,1
IF (N_ELEMENTS(PLT_DEV) EQ 0) THEN PLT_DEV=''
IF PLT_DEV NE '' THEN SET_PLOT,PLT_DEV ELSE RETURN
DEVICE,/CLOSE
PLT_DEV=''
IF N_ELEMENTS(DEV) NE 0 THEN SET_PLOT,DEV
RETURN
END

