# This file was automatically generated by SWIG
package a3dif;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package a3dif;
bootstrap a3dif;
var_a3dif_init();
@EXPORT = qw( );
1;
