# This file was automatically generated by SWIG
package libhef;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package libhefc;
bootstrap libhef;
package libhef;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package libhef;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package libhef;

*a3opencyclefile = *libhefc::a3opencyclefile;
*a3closecyclefile = *libhefc::a3closecyclefile;
*a3readcycle = *libhefc::a3readcycle;
*a3expand = *libhefc::a3expand;
*a3gtime = *libhefc::a3gtime;
*a3zrecid = *libhefc::a3zrecid;
*a3hdffn = *libhefc::a3hdffn;
*a3ncfver = *libhefc::a3ncfver;
*a3gdpuhk = *libhefc::a3gdpuhk;
*a3cycx_nominal = *libhefc::a3cycx_nominal;
*a3gxeqdpu_i = *libhefc::a3gxeqdpu_i;
*a3gxeqtab_i = *libhefc::a3gxeqtab_i;
*a3gxeqaux_i = *libhefc::a3gxeqaux_i;
*a3gxpavdpu = *libhefc::a3gxpavdpu;
*a3xpavlev = *libhefc::a3xpavlev;
*a3xadc = *libhefc::a3xadc;
*a3xtrigcal = *libhefc::a3xtrigcal;
*a3xtrigmode = *libhefc::a3xtrigmode;
*a3gcnq = *libhefc::a3gcnq;
*a3gcnm = *libhefc::a3gcnm;
*a3gbrtab = *libhefc::a3gbrtab;
*a3gmrtab = *libhefc::a3gmrtab;
*a3gxhk = *libhefc::a3gxhk;
*a3gxfsr_i = *libhefc::a3gxfsr_i;
*a3gxdcr_i = *libhefc::a3gxdcr_i;
*a3gxtcr_i = *libhefc::a3gxtcr_i;
*a3gxsdr_i = *libhefc::a3gxsdr_i;
*a3gxpr_i = *libhefc::a3gxpr_i;
*a3gxar_i = *libhefc::a3gxar_i;
*a3gxmr = *libhefc::a3gxmr;
*a3gxmr_i = *libhefc::a3gxmr_i;
*a3gxbr = *libhefc::a3gxbr;
*a3xbrwgt = *libhefc::a3xbrwgt;
*a3xnpha = *libhefc::a3xnpha;
*a3gxnr = *libhefc::a3gxnr;
*a3gxmoq_i = *libhefc::a3gxmoq_i;
*a3gxmas_i = *libhefc::a3gxmas_i;
*a3gxtof_i = *libhefc::a3gxtof_i;
*a3gxesd_i = *libhefc::a3gxesd_i;
*a3gxdid_i = *libhefc::a3gxdid_i;
*a3gxsec_i = *libhefc::a3gxsec_i;
*a3gxrng_i = *libhefc::a3gxrng_i;
*a3cxmoq = *libhefc::a3cxmoq;
*a3cxmas = *libhefc::a3cxmas;
*a3xellmmq = *libhefc::a3xellmmq;
*a3xrell = *libhefc::a3xrell;
*a3xelletm = *libhefc::a3xelletm;
*a3mmq = *libhefc::a3mmq;
*a3eth = *libhefc::a3eth;
*a3qth = *libhefc::a3qth;
*a3xmrspd = *libhefc::a3xmrspd;
*a3auxspd = *libhefc::a3auxspd;
*a3xeoqsumv1 = *libhefc::a3xeoqsumv1;
*a3cycm_nominal = *libhefc::a3cycm_nominal;
*a3ccycm = *libhefc::a3ccycm;
*a3ccycm_mcalev = *libhefc::a3ccycm_mcalev;
*a3ccycm_mcolev = *libhefc::a3ccycm_mcolev;
*a3ccycm_hyplev = *libhefc::a3ccycm_hyplev;
*a3ccycm_eqhk = *libhefc::a3ccycm_eqhk;
*a3ccycm_eqtabnom = *libhefc::a3ccycm_eqtabnom;
*a3gmeqdpu_i = *libhefc::a3gmeqdpu_i;
*a3mhyplev = *libhefc::a3mhyplev;
*a3gmhk = *libhefc::a3gmhk;
*a3mbrwgt = *libhefc::a3mbrwgt;
*a3gmfsr_i = *libhefc::a3gmfsr_i;
*a3gmfsra_i = *libhefc::a3gmfsra_i;
*a3gmfsrb_i = *libhefc::a3gmfsrb_i;
*a3gmfsrab_i = *libhefc::a3gmfsrab_i;
*a3gmrsr_i = *libhefc::a3gmrsr_i;
*a3gmdcr_i = *libhefc::a3gmdcr_i;
*a3gmmfsr_i = *libhefc::a3gmmfsr_i;
*a3gmmdcr_i = *libhefc::a3gmmdcr_i;
*a3mnpha = *libhefc::a3mnpha;
*a3gmdid = *libhefc::a3gmdid;
*a3gmsec = *libhefc::a3gmsec;
*a3gmstamp = *libhefc::a3gmstamp;
*a3gmstopk1 = *libhefc::a3gmstopk1;
*a3gmstopk2 = *libhefc::a3gmstopk2;
*a3gmtof = *libhefc::a3gmtof;
*a3cmtof = *libhefc::a3cmtof;
*a3mcntpha = *libhefc::a3mcntpha;
*a3mtofhist = *libhefc::a3mtofhist;
*a3mtof1_i = *libhefc::a3mtof1_i;
*a3mtof2_i = *libhefc::a3mtof2_i;
*a3gshk = *libhefc::a3gshk;
*a3gxeqtab = *libhefc::a3gxeqtab;
*a3gxeqdpu = *libhefc::a3gxeqdpu;
*a3gxfsr = *libhefc::a3gxfsr;
*a3gxdcr = *libhefc::a3gxdcr;
*a3gxtcr = *libhefc::a3gxtcr;
*a3gxsdr = *libhefc::a3gxsdr;
*a3gxpr = *libhefc::a3gxpr;
*a3gxar = *libhefc::a3gxar;
*a3gmeqtab = *libhefc::a3gmeqtab;
*a3gmeqtab_i = *libhefc::a3gmeqtab_i;
*a3gmeqdpu = *libhefc::a3gmeqdpu;
*a3gxmoq = *libhefc::a3gxmoq;
*a3gxmas = *libhefc::a3gxmas;
*adputof = *libhefc::adputof;
*adpuesd = *libhefc::adpuesd;
*adpumoq = *libhefc::adpumoq;
*adpumas = *libhefc::adpumas;
*adpueoq = *libhefc::adpueoq;
*xfm = *libhefc::xfm;
*xeffv1 = *libhefc::xeffv1;
*aget = *libhefc::aget;
*aset = *libhefc::aset;
*aeset = *libhefc::aeset;
*asum = *libhefc::asum;
*aadd = *libhefc::aadd;
*dmom1 = *libhefc::dmom1;
*dmomN = *libhefc::dmomN;
*I = *libhefc::I;
*I3 = *libhefc::I3;
*dvec_get = *libhefc::dvec_get;
*dvec_free = *libhefc::dvec_free;
*libhefrev = *libhefc::libhefrev;
*sec70_time = *libhefc::sec70_time;
*doy_time = *libhefc::doy_time;
*date_time = *libhefc::date_time;
*timstr = *libhefc::timstr;
*ltcaldat = *libhefc::ltcaldat;
*ltjulday = *libhefc::ltjulday;
*is_leap = *libhefc::is_leap;
*perr_setlevel = *libhefc::perr_setlevel;

# ------- VARIABLE STUBS --------

package libhef;

1;
