/* $Id: sepica.h,v 1.7 1998/03/24 16:42:57 asc Exp $ */

#include "s3_shk1.h"
#include "s3_shk2.h"
#include "s3_shk3.h"
#include "s3_shk4.h"
#include "s3_shk5.h"
#include "s3_smatrix.h"
#include "s3_smonitor.h"
#include "s3_ssector.h"
#include "s3_sbasic.h"
#include "s3_sstatus.h"
#include "s3_spha.h"
#include "s3_sdiag.h"
#include "sepica_rwbr.h"
#include "s3_dspare_class.h"
#include "s3_dspare_cmd.h"
#include "s3_dspare_contr.h"
#include "s3_dspare_alarm.h"
#include "s3_dspare_alarmcnt.h"
